### ISSUE TITLE
how to cal the distance between the tag and camera?

### ISSUE THREAD

**Issue by BlackJocker1995** [swatbotics/apriltags-cpp#15]
At first, i appreciate you sincerely.just i have some question about apriltag that how dose it calcuate the distance between the tag and camera in 3D? in other words，how to know the tag`s pose?Its x,y,z in  coordinate system.

**Comment by SonOfCoding** [comment]
have you solved question? i have the same problem

**Comment by BlackJocker1995** [comment]
I looked  up  some informations  and got that  if  you want to know  the distance  between camera  and tag, you need know accurate focus which we  can not get early on  normal  camera.
