### ISSUE TITLE
how to run the demo??

### ISSUE THREAD

**Issue by SonOfCoding** [swatbotics/apriltags-cpp#19]
i have installed it and I tried to run the demo camtest. But it shows:

edison@edison-Vostro-3668:~/kinect/apriltags-cpp/build$ ./camtest
family.minimumHammingDistance = 11
family.errorRecoveryBits = 5
Set camera to resolution: 0x0
no frames!

there is no window for detecting, can you please help me? thank you

**Comment by ptrsr** [comment]
Set the resolution to something like 1280x720 and try again
